//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquitecturaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasDocente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentasDocente()
        {
            this.Maestro_Tesis = new HashSet<Maestro_Tesis>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_facultad { get; set; }
        public Nullable<int> id_datos { get; set; }
    
        public virtual Facultades Facultades { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maestro_Tesis> Maestro_Tesis { get; set; }
    }
}
