//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquitecturaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TareaGrupalEntities : DbContext
    {
        public TareaGrupalEntities()
            : base("name=TareaGrupalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carreras> Carreras { get; set; }
        public virtual DbSet<CuentasDocente> CuentasDocente { get; set; }
        public virtual DbSet<EstudiantesTesis> EstudiantesTesis { get; set; }
        public virtual DbSet<Facultades> Facultades { get; set; }
        public virtual DbSet<Géneros> Géneros { get; set; }
        public virtual DbSet<Informes> Informes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
