//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquitecturaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestro_Tesis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maestro_Tesis()
        {
            this.Actividades = new HashSet<Actividades>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_docente { get; set; }
        public Nullable<int> id_estudiante { get; set; }
        public Nullable<int> mesAP { get; set; }
        public Nullable<int> añoAP { get; set; }
        public string tema { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividades> Actividades { get; set; }
        public virtual CuentasDocente CuentasDocente { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
    }
}
